import Header from './components/HeaderFooter/Header';
import Footer from './components/HeaderFooter/Footer';
import "./globals.css";

export default function Home() {
  return (
    <div className="page">
      <Header />
	  {/*conteudo*/}
      {/* <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
      <p>asfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfdgasfd</p>
       */}
	    <Footer />
    </div>
  );
}